/**/*:
  ros__parameters:
    broker:
      host: "$MQTT_HOST"
      port: $MQTT_PORT
      user: "$MQTT_USER"
      pass: "$MQTT_PASS"
      tls:
        enabled: true
    client:
      id: utrecht
      clean_session: true
      keep_alive_interval: 25.0
    bridge:
      ros2mqtt:
        ros_topics:
          - /robot/temp_1
          - /robot/beta_1
          - /robot/beta_2
          - /robot/beta_3
          - /robot/gamma
          - /robot/alpha
          - /robot/gripper
          - /robot/buttons
        /robot/temp_1:
          mqtt_topic: robot/temp_1
        /robot/beta_1:
          mqtt_topic: robot/beta_1
        /robot/beta_2:
          mqtt_topic: robot/beta_2
        /robot/beta_3:
          mqtt_topic: robot/beta_3
        /robot/gamma:
          mqtt_topic: robot/gamma
        /robot/alpha:
          mqtt_topic: robot/alpha
        /robot/gripper:
          mqtt_topic: robot/gripper
        /robot/buttons:
          mqtt_topic: robot/buttons
      mqtt2ros:
        mqtt_topics:
          - robot/motor_1
          - robot/servo_1
          - robot/servo_2
          - robot/servo_3
          - robot/servo_4
          - robot/servo_5
          - robot/servo_6
        robot/motor_1:
          ros_topic: /robot/motor_1
        robot/servo_1:
          ros_topic: /robot/servo_1
        robot/servo_2:
          ros_topic: /robot/servo_2
        robot/servo_3:
          ros_topic: /robot/servo_3
        robot/servo_4:
          ros_topic: /robot/servo_4
        robot/servo_5:
          ros_topic: /robot/servo_5
        robot/servo_6:
          ros_topic: /robot/servo_6
